# Generated by Django 5.2.4 on 2025-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='boats/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='main_image',
        ),
        migrations.AddField(
            model_name='tour',
            name='boats',
            field=models.ManyToManyField(blank=True, to='tours.boat'),
        ),
    ]
