# Generated by Django 5.2.4 on 2025-07-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_boat_remove_tour_created_at_remove_tour_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="e.g., 'fas fa-wifi'", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AlterField(
            model_name='tour',
            name='boats',
            field=models.ManyToManyField(blank=True, help_text='اختر المراكب / الصور لعرضها في معرض الصور', to='tours.boat'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='لعرضها في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(help_text='خط السير اليومي المفصل'),
        ),
        migrations.AddField(
            model_name='tour',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='اختر المميزات والرفاهيات المتاحة في هذه الرحلة', to='tours.amenity'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard, Luxe, Deluxe', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField(help_text='أدخل ميزة واحدة في كل سطر')),
                ('sleeps', models.PositiveIntegerField(default=1, help_text='عدد الأفراد')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tours.tour')),
            ],
        ),
    ]
