# Generated by Django 5.2.4 on 2025-07-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_amenity_remove_tour_price_alter_tour_boats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Select the amenities available on this tour', to='tours.amenity'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='boats',
            field=models.ManyToManyField(blank=True, help_text='Select boats/images for the gallery', to='tours.boat'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='This is the main overview of the tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='For displaying on the homepage'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(help_text='The detailed day-by-day plan'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='benefits',
            field=models.TextField(help_text='Enter one benefit per line'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='sleeps',
            field=models.PositiveIntegerField(default=1, help_text='Number of people'),
        ),
        migrations.CreateModel(
            name='BoatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boats/gallery/')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.boat')),
            ],
        ),
    ]
