# Generated by Django 5.2.4 on 2025-07-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_boat_image_alter_tour_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='اختر المميزات والرفاهيات المتاحة في هذه الرحلة', to='tours.amenity'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='boats',
            field=models.ManyToManyField(blank=True, help_text='اختر المراكب / الصور لعرضها في معرض الصور', to='tours.boat'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='لعرضها في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(help_text='خط السير اليومي المفصل'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='sleeps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.packagecategory'),
        ),
    ]
