# Generated by Django 5.2.4 on 2025-07-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_packagecategory_alter_tour_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='boats',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='boat',
            field=models.ForeignKey(help_text='اختر المركب الخاص بهذه الباقة لعرض صوره', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.boat'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='sleeps',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
