# Generated by Django 5.2.4 on 2025-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tour_boats_tourpackage_boat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='boat',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='boats',
            field=models.ManyToManyField(blank=True, help_text='اختر مركبًا أو أكثر لهذه الباقة', to='tours.boat'),
        ),
    ]
