# Generated by Django 5.2.4 on 2025-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tourpackage_boat_tourpackage_boats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='amenities',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='tours.amenity'),
        ),
    ]
