# Generated by Django 5.2.4 on 2025-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='tour',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='الرفاهيات الأساسية للرحلة', to='tours.amenity'),
        ),
    ]
