# Generated by Django 5.2.4 on 2025-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_hotel_hotellocation_tourpackage_hotels_hotelimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='الرفاهيات الخاصة بهذه الباقة', to='tours.amenity'),
        ),
    ]
