# Generated by Django 5.2.4 on 2025-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tourpackage_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
