# Generated by Django 5.2.4 on 2025-07-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_hotel_price_per_night_alter_tourpackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(related_name='activities', to='tours.category'),
        ),
        migrations.CreateModel(
            name='CategoryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.category')),
            ],
        ),
    ]
