# Generated by Django 5.2.4 on 2025-07-19 13:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_activity_categories_categorygalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_hotels',
            field=models.ManyToManyField(blank=True, help_text='اختر الفنادق المميزة التي تريد عرضها في صفحة هذه المدينة.', related_name='featured_in_categories', to='tours.hotel'),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
    ]
