# Generated by Django 5.2.4 on 2025-07-22 10:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_category_description_category_featured_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='additional_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='tours.amenity'),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='stars',
            field=models.IntegerField(default=3, help_text='Star rating from 1 to 5'),
        ),
    ]
