# Generated by Django 5.2.4 on 2025-07-22 10:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_hotelimage_additional_details_hotelimage_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='stars',
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='tours.amenity'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3, help_text='Star rating from 1 to 5'),
        ),
    ]
