# Generated by Django 5.2.4 on 2025-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_hotelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='tour',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tour',
            field=models.ManyToManyField(related_name='packages', to='tours.tour'),
        ),
    ]
