# Generated by Django 5.2.4 on 2025-10-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_remove_tourpackage_tour_tourpackage_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/cards/'),
        ),
    ]
