# Generated by Django 5.2.4 on 2025-10-17 16:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_tour_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_ar',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_de',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_es',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_fr',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ru',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_zh_cn',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_zh_cn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_zh_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='description_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_zh_cn',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا النبذة التعريفية عن المدينة.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='highlights_text_zh_cn',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='اكتب هنا عن أبرز الأماكن والشواطئ.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorygalleryimage',
            name='caption_zh_cn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_zh_cn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_details_zh_cn',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_zh_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellocation',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_zh_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='name_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ar',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_de',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_es',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_fr',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_zh_cn',
            field=models.TextField(help_text='هذه هي النظرة العامة للرحلة', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_zh_cn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_zh_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='benefits_zh_cn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name_zh_cn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
