# Generated by Django 5.2.4 on 2025-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_activity_description_ar_activity_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_categories',
            field=models.BooleanField(default=True, help_text='✅ اعرض هذه الفئة في قائمة الفئات بالصفحة الرئيسية'),
        ),
    ]
